#############################################################
#
# ti-dm365-codecs-mpeg4enc
#
#############################################################

TI_DM365_CODECS_MPEG4ENC_VERSION = 02_00_00_10
TI_DM365_CODECS_MPEG4ENC_BASE = dm365_mpeg4enc_hdvicp_$(TI_DM365_CODECS_MPEG4ENC_VERSION)_production
TI_DM365_CODECS_MPEG4ENC_SOURCE = $(TI_DM365_CODECS_MPEG4ENC_BASE).bin
TI_DM365_CODECS_MPEG4ENC_SITE = http://software-dl.ti.com/dsps/dsps_public_sw/codecs/DM365/DM365_latest

TI_DM365_CODECS_MPEG4ENC_INSTALL_STAGING = YES
TI_DM365_CODECS_MPEG4ENC_INSTALL_TARGET = NO

TI_CODECS_INSTALL_DIR_RECIPE = /usr/share/ti/ti-codecs
TI_CODECS_INSTALL_DIR = $(STAGING_DIR)$(TI_CODECS_INSTALL_DIR_RECIPE)

define TI_DM365_CODECS_MPEG4ENC_EXTRACT_CMDS
	chmod +x $(DL_DIR)/$(TI_DM365_CODECS_MPEG4ENC_SOURCE)
	HOME=$(BUILD_DIR) $(DL_DIR)/$(TI_DM365_CODECS_MPEG4ENC_SOURCE) --mode silent
	cd $(BUILD_DIR)/$(TI_DM365_CODECS_MPEG4ENC_BASE) && tar xf $(TI_DM365_CODECS_MPEG4ENC_BASE).tar
        mv $(BUILD_DIR)/$(TI_DM365_CODECS_MPEG4ENC_BASE)/$(TI_DM365_CODECS_MPEG4ENC_BASE)/* $(@D)
        rm -fr $(BUILD_DIR)/$(TI_DM365_CODECS_MPEG4ENC_BASE)/
endef

define TI_DM365_CODECS_MPEG4ENC_INSTALL_STAGING_CMDS
	$(INSTALL) -d $(TI_CODECS_INSTALL_DIR)
	cp -pPrf $(@D)/* $(TI_CODECS_INSTALL_DIR)
endef

$(eval $(generic-package))
