#!/bin/sh

case "$1" in
start)
    echo "Starting GStreamer Daemon"
    nice -n -20 /usr/bin/gstd --system &
    ;;

stop)
    echo "Stoping GStreamer Daemon"
    killall gstd
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

