#!/bin/sh
#
# Start the USB devices
#

case "$1" in
  start)
	echo "Turn on USB devices..."
	modprobe musb_hdrc.ko
	modprobe davinci.ko
	modprobe udc_core.ko
	modprobe g_ether.ko
	#modprobe g_serial.ko
	;;
  stop)
	echo -n "Stopping USB devices..."
	#rmmod g_serial.ko
	rmmod g_ether.ko
	rmmod udc_core.ko
	rmmod davinci.ko
	rmmod musb_hdrc.ko
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
