#!/bin/sh
#
# Start the onboard Wi-Fi
#

# Check uEnv parameter "wifi=on"

CMDLINE=`cat /proc/cmdline | grep "wifi=on"`

if [ ! "$CMDLINE" == "" ]; then
    echo "Wi-Fi onboard module enabled"
else
    echo "Wi-Fi onboard module disabled"
    exit 1
fi

case "$1" in
  start)
	IF0=`cat /tmp/ifstate`
	if [ ! "$IF0" == "wlan0=wlan0" ]; then
	    echo "wlan0 not found, waiting 5 seconds..."
	    sleep 5
	fi
	
	echo "Starting Wi-Fi..."
	/usr/sbin/wpa_supplicant -Dwext -iwlan0 -c /etc/wpa_supplicant.conf -B
	/usr/sbin/wpa_cli -B -a /etc/virt2real/wlanchanged.sh
	;;
  stop)
	echo -n "Stopping Wi-Fi..."
	killall wpa_supplicant
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

