#!/bin/sh
#
# Start the onboard Wi-Fi
#

APADDR=192.168.2.1


# Check uEnv parameter "wifi=on"

CMDLINE=`cat /proc/cmdline | grep "wifi=on"`
AP=`cat /proc/cmdline | grep "ap=on"`

if [ ! "$CMDLINE" == "" ]; then
    echo "Wi-Fi onboard module enabled"
else
    echo "Wi-Fi onboard module disabled"
    exit 1
fi

case "$1" in
  start)
	if [ ! "$AP" = "" ] ; then 
		echo "Starting acces point..."
		modprobe uap8xxx.ko
		ifconfig uap0 $APADDR up
		/etc/virt2real/ap.sh &
		exit
	fi


	echo "Starting Wi-Fi client..."
	
	/etc/virt2real/wlan.sh &
	
	;;
  stop)
	echo -n "Stopping Wi-Fi..."
	killall wpa_supplicant
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

