#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	#echo "Starting network..."
	#/sbin/ifup -a -f

 	echo "Starting network async..."
	/sbin/ifup -a -f 2>&1 > /dev/null &
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


