#!/bin/sh

case "$1" in
start)
    echo "Starting dontsleep script..."

	# turn on wi-fi don't sleep script
	/etc/virt2real/dontsleep.sh &
    ;;

stop)
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
