#!/bin/sh

case "$1" in
start)
    echo "Starting MJPEG server..."
    /etc/virt2real/mjpeg_server.sh start > /dev/null &
    ;;

stop)
    echo "Stopping MJPEG server..."
    /etc/virt2real/mjpeg_server.sh stop > /dev/null &
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
