#!/bin/sh

case "$1" in
start)
    echo "Starting RTSP server..."
    /etc/virt2real/rtsp_server.sh > /dev/null &
    ;;

stop)
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
