#!/bin/sh

case "$1" in
start)
    echo "Starting RTMP client..."
    /etc/virt2real/rtmp_client.sh start > /dev/null &
    ;;

stop)
    echo "Stopping RTMP client..."
    /etc/virt2real/rtmp_client.sh stop > /dev/null &
    ;;

*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
