#!/bin/sh
#
# $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
#

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".

INTERFACES="uap0 wlan0 usb0"

test ! -f /usr/sbin/dhcpd && exit 0

case "$1" in
	start)
		echo -n "Starting DHCP server: "
		test ! -d /var/lib/dhcp/ && mkdir -p /var/lib/dhcp/
		test ! -f /var/lib/dhcp/dhcpd.leases && touch /var/lib/dhcp/dhcpd.leases
		test ! -f /etc/dhcpd.conf && ln -s /etc/dhcp/dhcpd.conf /etc/dhcpd.conf > /dev/null
		test -f /var/run/dhcpd.pid && rm /var/run/dhcpd.pid > /dev/null
		start-stop-daemon -S -x /usr/sbin/dhcpd  -q $INTERFACES
		echo "."
		;;
	stop)
		echo -n "Stopping DHCP server: dhcpd3"
		start-stop-daemon -K -x /usr/sbin/dhcpd
		echo "."
		;;
	restart | force-reload)
		$0 stop
		sleep 2
		$0 start
		if [ "$?" != "0" ]; then
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/dhcp-server {start|stop|restart|force-reload}"
		exit 1 
esac

exit 0
